/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.telas;

import br.com.smartmall.Controle_de_Fornecedor;
import br.com.smartmall.Endereco;
import br.com.smartmall.Fornecedor;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author Thejotta
 */
public class TFornecedor extends javax.swing.JFrame {
     private Fornecedor fornecedor;
     private Endereco endereco;
     private Controle_de_Fornecedor cfornecedor;
    /**
     * Creates new form TGFornecedor
     */
    public TFornecedor() {
        fornecedor=new Fornecedor();
        endereco=new Endereco();
        cfornecedor=new Controle_de_Fornecedor();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelFornecedor = new javax.swing.JTabbedPane();
        PanelCadastrarFornecedor = new javax.swing.JPanel();
        PanelDadosFornecedor1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        TNomeFor = new javax.swing.JTextField();
        TCNPJFor = new javax.swing.JTextField();
        TTelefoneFor = new javax.swing.JTextField();
        PanelEnderecoFornecedor1 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        TBairroFor = new javax.swing.JTextField();
        TCEPFor = new javax.swing.JTextField();
        TNunFor = new javax.swing.JTextField();
        TCidadeFor = new javax.swing.JTextField();
        TCompFor = new javax.swing.JTextField();
        TLogFor = new javax.swing.JTextField();
        BCadasFor = new javax.swing.JButton();
        BCancFor1 = new javax.swing.JButton();
        PanelGerenciarFornecedor = new javax.swing.JPanel();
        PanelPesquisarFornecedor = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        TCNPJPesqFor = new javax.swing.JTextField();
        BPesFor = new javax.swing.JButton();
        PanelAtuExcFornecedor = new javax.swing.JPanel();
        PanelDadosFornecedor2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        TNomeFor1 = new javax.swing.JTextField();
        TCNPJFor1 = new javax.swing.JTextField();
        TTelefoneFor1 = new javax.swing.JTextField();
        PanelEnderecoFornecedor2 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        TLogFor1 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        TBairroFor1 = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        TCidadeFor1 = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        TCEPFor1 = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        TNunFor1 = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        TCompFor1 = new javax.swing.JTextField();
        BAtualizarFor = new javax.swing.JButton();
        BExcluirFor = new javax.swing.JButton();
        BCancFor2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Fornecedor");

        PanelDadosFornecedor1.setBorder(javax.swing.BorderFactory.createTitledBorder("Dados do fornecedor"));

        jLabel1.setText("Nome: *");

        jLabel2.setText("CNPJ: *");

        jLabel3.setText("Telefone: *");

        TNomeFor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TNomeForActionPerformed(evt);
            }
        });

        TCNPJFor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TCNPJForActionPerformed(evt);
            }
        });
        TCNPJFor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TCNPJForKeyTyped(evt);
            }
        });

        TTelefoneFor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TTelefoneForActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelDadosFornecedor1Layout = new javax.swing.GroupLayout(PanelDadosFornecedor1);
        PanelDadosFornecedor1.setLayout(PanelDadosFornecedor1Layout);
        PanelDadosFornecedor1Layout.setHorizontalGroup(
            PanelDadosFornecedor1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelDadosFornecedor1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelDadosFornecedor1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PanelDadosFornecedor1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TCNPJFor, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TNomeFor, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TTelefoneFor, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PanelDadosFornecedor1Layout.setVerticalGroup(
            PanelDadosFornecedor1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelDadosFornecedor1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelDadosFornecedor1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(TNomeFor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelDadosFornecedor1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(TCNPJFor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelDadosFornecedor1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(TTelefoneFor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        PanelEnderecoFornecedor1.setBorder(javax.swing.BorderFactory.createTitledBorder("Endereço do fornecedor"));

        jLabel8.setText("Bairro: *");

        jLabel9.setText("Cidade: *");

        jLabel10.setText("CEP: *");

        jLabel11.setText("Numero: *");

        jLabel12.setText("Logradouro: *");

        jLabel13.setText("Complemento:");

        TCEPFor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TCEPForKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout PanelEnderecoFornecedor1Layout = new javax.swing.GroupLayout(PanelEnderecoFornecedor1);
        PanelEnderecoFornecedor1.setLayout(PanelEnderecoFornecedor1Layout);
        PanelEnderecoFornecedor1Layout.setHorizontalGroup(
            PanelEnderecoFornecedor1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelEnderecoFornecedor1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelEnderecoFornecedor1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelEnderecoFornecedor1Layout.createSequentialGroup()
                        .addGroup(PanelEnderecoFornecedor1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(PanelEnderecoFornecedor1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TCEPFor, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TBairroFor, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(PanelEnderecoFornecedor1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel11))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(PanelEnderecoFornecedor1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PanelEnderecoFornecedor1Layout.createSequentialGroup()
                                .addComponent(TNunFor, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 51, Short.MAX_VALUE))
                            .addComponent(TCidadeFor))
                        .addContainerGap())
                    .addGroup(PanelEnderecoFornecedor1Layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TCompFor)
                        .addGap(10, 10, 10))
                    .addGroup(PanelEnderecoFornecedor1Layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TLogFor)
                        .addContainerGap())))
        );
        PanelEnderecoFornecedor1Layout.setVerticalGroup(
            PanelEnderecoFornecedor1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelEnderecoFornecedor1Layout.createSequentialGroup()
                .addContainerGap(38, Short.MAX_VALUE)
                .addGroup(PanelEnderecoFornecedor1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(TLogFor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PanelEnderecoFornecedor1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addComponent(TBairroFor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TCidadeFor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelEnderecoFornecedor1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11)
                    .addComponent(TCEPFor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TNunFor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelEnderecoFornecedor1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(TCompFor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26))
        );

        BCadasFor.setText("Cadastrar");
        BCadasFor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BCadasForActionPerformed(evt);
            }
        });

        BCancFor1.setText("Cancelar");
        BCancFor1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BCancFor1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelCadastrarFornecedorLayout = new javax.swing.GroupLayout(PanelCadastrarFornecedor);
        PanelCadastrarFornecedor.setLayout(PanelCadastrarFornecedorLayout);
        PanelCadastrarFornecedorLayout.setHorizontalGroup(
            PanelCadastrarFornecedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelCadastrarFornecedorLayout.createSequentialGroup()
                .addGroup(PanelCadastrarFornecedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelCadastrarFornecedorLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(PanelDadosFornecedor1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(PanelCadastrarFornecedorLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(PanelEnderecoFornecedor1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(PanelCadastrarFornecedorLayout.createSequentialGroup()
                .addGap(112, 112, 112)
                .addComponent(BCadasFor)
                .addGap(42, 42, 42)
                .addComponent(BCancFor1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PanelCadastrarFornecedorLayout.setVerticalGroup(
            PanelCadastrarFornecedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelCadastrarFornecedorLayout.createSequentialGroup()
                .addComponent(PanelDadosFornecedor1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(PanelEnderecoFornecedor1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(PanelCadastrarFornecedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BCadasFor)
                    .addComponent(BCancFor1))
                .addContainerGap(42, Short.MAX_VALUE))
        );

        PanelFornecedor.addTab("Cadastrar fornecedor", PanelCadastrarFornecedor);

        PanelPesquisarFornecedor.setBorder(javax.swing.BorderFactory.createTitledBorder("Pesquisar fornecedor"));
        PanelPesquisarFornecedor.setToolTipText("");

        jLabel4.setText("CNPJ:");

        TCNPJPesqFor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TCNPJPesqForActionPerformed(evt);
            }
        });
        TCNPJPesqFor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TCNPJPesqForKeyTyped(evt);
            }
        });

        BPesFor.setText("Pesquisar");
        BPesFor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BPesForActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelPesquisarFornecedorLayout = new javax.swing.GroupLayout(PanelPesquisarFornecedor);
        PanelPesquisarFornecedor.setLayout(PanelPesquisarFornecedorLayout);
        PanelPesquisarFornecedorLayout.setHorizontalGroup(
            PanelPesquisarFornecedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelPesquisarFornecedorLayout.createSequentialGroup()
                .addGap(93, 93, 93)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TCNPJPesqFor, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BPesFor)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PanelPesquisarFornecedorLayout.setVerticalGroup(
            PanelPesquisarFornecedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelPesquisarFornecedorLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelPesquisarFornecedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TCNPJPesqFor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(BPesFor))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        PanelAtuExcFornecedor.setBorder(javax.swing.BorderFactory.createTitledBorder("Atualizar/Encluir fornecedor"));

        PanelDadosFornecedor2.setBorder(javax.swing.BorderFactory.createTitledBorder("Dados do fornecedor"));

        jLabel5.setText("Nome: *");

        jLabel6.setText("CNPJ: *");

        jLabel7.setText("Telefone: *");

        TNomeFor1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TNomeFor1ActionPerformed(evt);
            }
        });

        TCNPJFor1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TCNPJFor1ActionPerformed(evt);
            }
        });
        TCNPJFor1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TCNPJFor1KeyTyped(evt);
            }
        });

        TTelefoneFor1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TTelefoneFor1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelDadosFornecedor2Layout = new javax.swing.GroupLayout(PanelDadosFornecedor2);
        PanelDadosFornecedor2.setLayout(PanelDadosFornecedor2Layout);
        PanelDadosFornecedor2Layout.setHorizontalGroup(
            PanelDadosFornecedor2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelDadosFornecedor2Layout.createSequentialGroup()
                .addGroup(PanelDadosFornecedor2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(PanelDadosFornecedor2Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jLabel5))
                    .addGroup(PanelDadosFornecedor2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(PanelDadosFornecedor2Layout.createSequentialGroup()
                            .addGap(17, 17, 17)
                            .addComponent(jLabel6))
                        .addComponent(jLabel7)))
                .addGap(18, 18, 18)
                .addGroup(PanelDadosFornecedor2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TCNPJFor1, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TTelefoneFor1, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TNomeFor1, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PanelDadosFornecedor2Layout.setVerticalGroup(
            PanelDadosFornecedor2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelDadosFornecedor2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(PanelDadosFornecedor2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(TNomeFor1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(PanelDadosFornecedor2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(TCNPJFor1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelDadosFornecedor2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(TTelefoneFor1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        PanelEnderecoFornecedor2.setBorder(javax.swing.BorderFactory.createTitledBorder("Endereço do fornecedor"));

        jLabel14.setText("Logradouro: *");

        jLabel15.setText("Bairro: *");

        jLabel16.setText("Cidade: *");

        jLabel17.setText("CEP: *");

        TCEPFor1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TCEPFor1KeyTyped(evt);
            }
        });

        jLabel18.setText("Numero: *");

        jLabel19.setText("Complemento:");

        javax.swing.GroupLayout PanelEnderecoFornecedor2Layout = new javax.swing.GroupLayout(PanelEnderecoFornecedor2);
        PanelEnderecoFornecedor2.setLayout(PanelEnderecoFornecedor2Layout);
        PanelEnderecoFornecedor2Layout.setHorizontalGroup(
            PanelEnderecoFornecedor2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelEnderecoFornecedor2Layout.createSequentialGroup()
                .addGroup(PanelEnderecoFornecedor2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelEnderecoFornecedor2Layout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TLogFor1))
                    .addGroup(PanelEnderecoFornecedor2Layout.createSequentialGroup()
                        .addGroup(PanelEnderecoFornecedor2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(PanelEnderecoFornecedor2Layout.createSequentialGroup()
                                .addComponent(jLabel17)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(TCEPFor1, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(37, 37, 37)
                                .addComponent(jLabel18))
                            .addGroup(PanelEnderecoFornecedor2Layout.createSequentialGroup()
                                .addComponent(jLabel15)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(TBairroFor1, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel16)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(PanelEnderecoFornecedor2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TCidadeFor1, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TNunFor1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(PanelEnderecoFornecedor2Layout.createSequentialGroup()
                        .addComponent(jLabel19)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TCompFor1)))
                .addContainerGap())
        );
        PanelEnderecoFornecedor2Layout.setVerticalGroup(
            PanelEnderecoFornecedor2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelEnderecoFornecedor2Layout.createSequentialGroup()
                .addGroup(PanelEnderecoFornecedor2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(TLogFor1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelEnderecoFornecedor2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(TBairroFor1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16)
                    .addComponent(TCidadeFor1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelEnderecoFornecedor2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(TCEPFor1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18)
                    .addComponent(TNunFor1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelEnderecoFornecedor2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(TCompFor1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        BAtualizarFor.setText("Atualizar");
        BAtualizarFor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BAtualizarForActionPerformed(evt);
            }
        });

        BExcluirFor.setText("Excluir");

        BCancFor2.setText("Cancelar");
        BCancFor2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BCancFor2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelAtuExcFornecedorLayout = new javax.swing.GroupLayout(PanelAtuExcFornecedor);
        PanelAtuExcFornecedor.setLayout(PanelAtuExcFornecedorLayout);
        PanelAtuExcFornecedorLayout.setHorizontalGroup(
            PanelAtuExcFornecedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelAtuExcFornecedorLayout.createSequentialGroup()
                .addGroup(PanelAtuExcFornecedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelAtuExcFornecedorLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(PanelAtuExcFornecedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(PanelDadosFornecedor2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(PanelEnderecoFornecedor2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(PanelAtuExcFornecedorLayout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(BAtualizarFor)
                        .addGap(40, 40, 40)
                        .addComponent(BExcluirFor)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BCancFor2)
                        .addGap(38, 38, 38)))
                .addContainerGap())
        );
        PanelAtuExcFornecedorLayout.setVerticalGroup(
            PanelAtuExcFornecedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelAtuExcFornecedorLayout.createSequentialGroup()
                .addComponent(PanelDadosFornecedor2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PanelEnderecoFornecedor2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelAtuExcFornecedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BExcluirFor)
                    .addComponent(BCancFor2)
                    .addComponent(BAtualizarFor))
                .addGap(11, 11, 11))
        );

        javax.swing.GroupLayout PanelGerenciarFornecedorLayout = new javax.swing.GroupLayout(PanelGerenciarFornecedor);
        PanelGerenciarFornecedor.setLayout(PanelGerenciarFornecedorLayout);
        PanelGerenciarFornecedorLayout.setHorizontalGroup(
            PanelGerenciarFornecedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelGerenciarFornecedorLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelGerenciarFornecedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PanelPesquisarFornecedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(PanelAtuExcFornecedor, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        PanelGerenciarFornecedorLayout.setVerticalGroup(
            PanelGerenciarFornecedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelGerenciarFornecedorLayout.createSequentialGroup()
                .addComponent(PanelPesquisarFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PanelAtuExcFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        PanelPesquisarFornecedor.getAccessibleContext().setAccessibleName("");

        PanelFornecedor.addTab("Gerenciar fornecedor", PanelGerenciarFornecedor);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PanelFornecedor)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PanelFornecedor)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TNomeForActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TNomeForActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TNomeForActionPerformed

    private void TCNPJForActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TCNPJForActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TCNPJForActionPerformed
//função para verificar se existe algum campo vazio
    private boolean vazio(){
    
        return (TCEPFor.getText().isEmpty()     ||  TBairroFor.getText().isEmpty()  ||
                TCidadeFor.getText().isEmpty()  ||  TLogFor.getText().isEmpty()     ||
                TNunFor.getText().isEmpty()     ||  TNomeFor.getText().isEmpty()    ||
                TCNPJFor.getText().isEmpty()    ||  TTelefoneFor.getText().isEmpty());
    }
    
    //Função para limpar todos os campos do formulario
    private void LimparJtextfild(){
        TCEPFor.setText("");
        TBairroFor.setText("");
        TCidadeFor.setText("");
        TLogFor.setText("");
        TNunFor.setText("");
        TCompFor.setText("");
        TNomeFor.setText("");
        TCNPJFor.setText("");
        TTelefoneFor.setText("");
        TCompFor.setText("");
    }
    //função para preencher textfild
    private void setTextfild(Fornecedor fornecedor){
    TNomeFor1.setText(fornecedor.getNome_fornecedor());
    TCNPJFor1.setText(fornecedor.getCnpj());
    TTelefoneFor1.setText(fornecedor.getTelefone());
    TBairroFor1.setText(fornecedor.getEndereco().getBairro());
    TCEPFor1.setText(fornecedor.getEndereco().getCep());
    TCidadeFor1.setText(fornecedor.getEndereco().getCidade());
    TCompFor1.setText(fornecedor.getEndereco().getComplemento());
    TLogFor1.setText(fornecedor.getEndereco().getLongadouro());
    TNunFor1.setText(fornecedor.getEndereco().getNumero());
    }
    private void TCNPJForKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TCNPJForKeyTyped
        String caracteres="0987654321";
        //permitindo só numeros
        if(!caracteres.contains(evt.getKeyChar()+"")){
            evt.consume();
        }

        //tamanho maximo de caractres
        if((TCNPJFor.getText().length()>=14)&&(14!=-1)){
            evt.consume();
            TCNPJFor.setText(TCNPJFor.getText().substring(0,14));
        }
    }//GEN-LAST:event_TCNPJForKeyTyped

    private void TTelefoneForActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TTelefoneForActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TTelefoneForActionPerformed

    private void TCEPForKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TCEPForKeyTyped

        String caracteres="0987654321";
        //permitindo só numeros
        if(!caracteres.contains(evt.getKeyChar()+"")){
            evt.consume();
        }

        //tamanho maximo de caractres
        if((TCEPFor.getText().length()>=8)&&(8!=-1)){
            evt.consume();
            TCEPFor.setText(TCEPFor.getText().substring(0,8));
        }

    }//GEN-LAST:event_TCEPForKeyTyped

    private void BCadasForActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BCadasForActionPerformed

        if(!vazio()){
            //Obtendo valores dos textfild referente a endereço
            endereco.setCep(TCEPFor.getText());
            endereco.setBairro(TBairroFor.getText());
            endereco.setCidade(TCidadeFor.getText());
            endereco.setLongadouro(TLogFor.getText());
            endereco.setNumero(TNunFor.getText());
            endereco.setComplemento(TCompFor.getText());

            //Obtendo valores dos textfild referente a fornecedor
            fornecedor.setNome_fornecedor(TNomeFor.getText());
            fornecedor.setCnpj(TCNPJFor.getText());
            fornecedor.setTelefone(TTelefoneFor.getText());
            fornecedor.setEndereco(endereco);

            cfornecedor.setEndereco(endereco);
            cfornecedor.setFornecedor(fornecedor);

            if(!cfornecedor.cadastrarEndereco() && !cfornecedor.cadastrarFornecedor()){
                JOptionPane.showMessageDialog(null, "Fornecedor cadastrado com sucesso!!");
                LimparJtextfild();
            }
        }else
        {
            JOptionPane.showMessageDialog(null, "Você deve preencher os campos com '*'");
        }
    }//GEN-LAST:event_BCadasForActionPerformed

    private void BCancFor1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BCancFor1ActionPerformed
        //Fechando form
        this.dispose();
    }//GEN-LAST:event_BCancFor1ActionPerformed

    private void TCNPJPesqForActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TCNPJPesqForActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TCNPJPesqForActionPerformed

    private void TCNPJPesqForKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TCNPJPesqForKeyTyped
        String caracteres="0987654321";
        //permitindo só numeros
        if(!caracteres.contains(evt.getKeyChar()+"")){
            evt.consume();
        }
        //tamanho maximo de caractres
        if((TCNPJPesqFor.getText().length()>=14)&&(14!=-1)){
            evt.consume();
            TCNPJPesqFor.setText(TCNPJPesqFor.getText().substring(0,14));
        }
    }//GEN-LAST:event_TCNPJPesqForKeyTyped

    private void BPesForActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BPesForActionPerformed
        cfornecedor=new Controle_de_Fornecedor();

        //verificando se o fornecedor existe no banco de dados
        if(cfornecedor.VerificarExistenciaFornecedor(TCNPJPesqFor.getText())){
            //fazendo pesquisa do fornecedor
            cfornecedor=new Controle_de_Fornecedor();

            //obtendo os dados do fornecedor
            List<Fornecedor> Lfornecedor = cfornecedor.pesquisarFornecedor(TCNPJPesqFor.getText());
            fornecedor=Lfornecedor.get(0);
            cfornecedor.setFornecedor(fornecedor);

            //obtendo o endereço do fornecedor
            List<Endereco> Lendereco =cfornecedor.pesquisarEndereco();
            endereco=Lendereco.get(0);
            cfornecedor.setEndereco(endereco);

            //preenchendo textfild da outra tela com os dados do fornecedor
            setTextfild(fornecedor);

        }else//mensagem de erro caso o fornecedor não exita
        JOptionPane.showMessageDialog(null, "Fornecedor não encontrado!!");
    }//GEN-LAST:event_BPesForActionPerformed

    private void TNomeFor1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TNomeFor1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TNomeFor1ActionPerformed

    private void TCNPJFor1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TCNPJFor1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TCNPJFor1ActionPerformed

    private void TCNPJFor1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TCNPJFor1KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_TCNPJFor1KeyTyped

    private void TTelefoneFor1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TTelefoneFor1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TTelefoneFor1ActionPerformed

    private void TCEPFor1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TCEPFor1KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_TCEPFor1KeyTyped

    private void BCancFor2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BCancFor2ActionPerformed
        //Fechando form
        this.dispose();
    }//GEN-LAST:event_BCancFor2ActionPerformed

    private void BAtualizarForActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BAtualizarForActionPerformed
            cfornecedor=new Controle_de_Fornecedor();
        //Obtendo valores dos textfild referente a endereço
            endereco.setCep(TCEPFor1.getText());
            endereco.setBairro(TBairroFor1.getText());
            endereco.setCidade(TCidadeFor1.getText());
            endereco.setLongadouro(TLogFor1.getText());
            endereco.setNumero(TNunFor1.getText());
            endereco.setComplemento(TCompFor1.getText());

            //Obtendo valores dos textfild referente a fornecedor
            fornecedor.setNome_fornecedor(TNomeFor1.getText());
            fornecedor.setCnpj(TCNPJFor1.getText());
            fornecedor.setTelefone(TTelefoneFor1.getText());
            fornecedor.setEndereco(endereco);
        
            cfornecedor.setFornecedor(fornecedor);
            cfornecedor.setEndereco(endereco);
            
            cfornecedor.atualizarFornecedor();
            cfornecedor.atualizarEndereco();
            JOptionPane.showMessageDialog(null, "Fornecedor alterado com sucesso!!");
    }//GEN-LAST:event_BAtualizarForActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TFornecedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TFornecedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TFornecedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TFornecedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TFornecedor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BAtualizarFor;
    private javax.swing.JButton BCadasFor;
    private javax.swing.JButton BCancFor1;
    private javax.swing.JButton BCancFor2;
    private javax.swing.JButton BExcluirFor;
    private javax.swing.JButton BPesFor;
    private javax.swing.JPanel PanelAtuExcFornecedor;
    private javax.swing.JPanel PanelCadastrarFornecedor;
    private javax.swing.JPanel PanelDadosFornecedor1;
    private javax.swing.JPanel PanelDadosFornecedor2;
    private javax.swing.JPanel PanelEnderecoFornecedor1;
    private javax.swing.JPanel PanelEnderecoFornecedor2;
    private javax.swing.JTabbedPane PanelFornecedor;
    private javax.swing.JPanel PanelGerenciarFornecedor;
    private javax.swing.JPanel PanelPesquisarFornecedor;
    private javax.swing.JTextField TBairroFor;
    private javax.swing.JTextField TBairroFor1;
    private javax.swing.JTextField TCEPFor;
    private javax.swing.JTextField TCEPFor1;
    private javax.swing.JTextField TCNPJFor;
    private javax.swing.JTextField TCNPJFor1;
    private javax.swing.JTextField TCNPJPesqFor;
    private javax.swing.JTextField TCidadeFor;
    private javax.swing.JTextField TCidadeFor1;
    private javax.swing.JTextField TCompFor;
    private javax.swing.JTextField TCompFor1;
    private javax.swing.JTextField TLogFor;
    private javax.swing.JTextField TLogFor1;
    private javax.swing.JTextField TNomeFor;
    private javax.swing.JTextField TNomeFor1;
    private javax.swing.JTextField TNunFor;
    private javax.swing.JTextField TNunFor1;
    private javax.swing.JTextField TTelefoneFor;
    private javax.swing.JTextField TTelefoneFor1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
