/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.telas;

import br.com.smartmall.Controle_de_Fornecedor;
import br.com.smartmall.Endereco;
import br.com.smartmall.Fornecedor;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author tawanna
 */
public class TPesquisarFornecedor extends javax.swing.JFrame {
     private Fornecedor fornecedor;
     private Endereco endereco;
     private Controle_de_Fornecedor cfornecedor;
     private TCadastrarFornecedor tcfornecedor;
    /**
     * Creates new form TPesquisarFornecedor
     */
    public TPesquisarFornecedor() {
        fornecedor=new Fornecedor();
        endereco=new Endereco();
        tcfornecedor= new TCadastrarFornecedor();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        BPesFor = new javax.swing.JButton();
        BCancPesfor = new javax.swing.JButton();
        TCNPJPesqFor = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Pesquisar Fornecedor");

        jLabel1.setText("CNPJ:");

        BPesFor.setText("Pesquisar");
        BPesFor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BPesForActionPerformed(evt);
            }
        });

        BCancPesfor.setText("Cancelar");
        BCancPesfor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BCancPesforActionPerformed(evt);
            }
        });

        TCNPJPesqFor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TCNPJPesqForActionPerformed(evt);
            }
        });
        TCNPJPesqFor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TCNPJPesqForKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(93, 93, 93)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(BPesFor)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BCancPesfor))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TCNPJPesqFor, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(103, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(TCNPJPesqFor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BPesFor)
                    .addComponent(BCancPesfor))
                .addContainerGap(58, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BCancPesforActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BCancPesforActionPerformed
        //Fechando form
        this.dispose();
    }//GEN-LAST:event_BCancPesforActionPerformed

    private void TCNPJPesqForActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TCNPJPesqForActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TCNPJPesqForActionPerformed

    private void BPesForActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BPesForActionPerformed
       cfornecedor=new Controle_de_Fornecedor();
        
       //verificando se o fornecedor existe no banco de dados
       if(cfornecedor.VerificarExistenciaFornecedor(TCNPJPesqFor.getText())){
        //fazendo pesquisa do fornecedor
        cfornecedor=new Controle_de_Fornecedor();
        
        //obtendo os dados do fornecedor
        List<Fornecedor> Lfornecedor = cfornecedor.pesquisarFornecedor(TCNPJPesqFor.getText());
        fornecedor=Lfornecedor.get(0);
        cfornecedor.setFornecedor(fornecedor);
        
        //obtendo o endereço do fornecedor
        List<Endereco> Lendereco =cfornecedor.pesquisarEndereco();
        endereco=Lendereco.get(0);
        cfornecedor.setEndereco(endereco);
        
        //preenchendo textfild da outra tela com os dados do fornecedor
        tcfornecedor.setTextfild(fornecedor);
        
        //Chamando outra tela
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                tcfornecedor.setVisible(true);
                }
        });
        
        //fechando tela atual
        this.dispose();
       }else//mensagem de erro caso o fornecedor não exita
           JOptionPane.showMessageDialog(null, "Fornecedor não encontrado!!");
    }//GEN-LAST:event_BPesForActionPerformed

    private void TCNPJPesqForKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TCNPJPesqForKeyTyped
      String caracteres="0987654321";
        //permitindo só numeros
        if(!caracteres.contains(evt.getKeyChar()+"")){
            evt.consume();
        } 
        //tamanho maximo de caractres
        if((TCNPJPesqFor.getText().length()>=14)&&(14!=-1)){ 
            evt.consume(); 
            TCNPJPesqFor.setText(TCNPJPesqFor.getText().substring(0,14)); 
        }
    }//GEN-LAST:event_TCNPJPesqForKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TPesquisarFornecedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TPesquisarFornecedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TPesquisarFornecedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TPesquisarFornecedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TPesquisarFornecedor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BCancPesfor;
    private javax.swing.JButton BPesFor;
    private javax.swing.JTextField TCNPJPesqFor;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
